name: azd catalog metadata

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  catalog:
    name: azd catalog metadata
    uses: nathanmcnulty/azd-reference/.github/workflows/catalog-metadata.yml@06d22bcf2ff819f8c0bfa58d6c67decbb9076c0b
    permissions:
      contents: read
